addition of autoencoder class.
Oxford-Dynamics-Repository/mindglass pull request #21
Opened 2022-10-06 17:17 UTC by Ljackson-su

Capability of working with video and images, Encode and decode reproduces the same video. Not yet tested in video diffusion pipeline

2022-10-06 19:40 UTC, oxjohanndiep requested changes
Went through the first review, request some changes. It would be nice if you can test it on mock data first, both the image and video encoder/decoder functions. This way you can be 100% about the individual dimensions.

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +        imgs = (imgs[0] / 2 + 0.5).clamp(0, 1)
Are you sure you need the 0-index here? 
imgs is of size [b, c, h, w] and imgs[0] would essentially take the first batch which has shape [c, h, w].
If you want to apply the de-normalization here, I believe it should be:
`imgs = (imgs / 2 + 0.5).clamp(0, 1)`

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +        imgs = imgs.detach().cpu().permute(0, 2, 3, 1).numpy()
This does not resize, it just permutes the order, from [b, c, h, w] to [b, h, w, c].

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +        video_by_batch = vid_array.float().permute(0, 2, 1, 3, 4)
Note: Change frame and channel order (from [b, c, f, h, w] to [b, f, c, h, w]).

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +        if vid.dim != 5:
Assuming the video comes as a tensor, it should be: `vid.dim()`

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +        for i in range (video_by_batch.shape[0]):
Note: This loops through the batches.

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +            latent_dists_1_video = self.model.encode(video_by_batch[i])
`video_by_batch[i]` still has shape [f, c, h, w], I believe it requires a cascaded loop through the frames.

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +            latent_samples.append(latent_sample)
Not sure if this creates the correct stacked dimension, I would rather use `torch.stack`: https://pytorch.org/docs/stable/generated/torch.stack.html

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +            latent_samples.append(latent_sample)
And stack it at dimension 1 such that the end dimension would be [b, f, 4, h/8, w/8)].

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +    # outputs: Encodings as tensor (b, 4, h/8, w/8)
Should be [b, f, 4, h/8, w/8], I believe you forgot the stacked frame embeddings per batch.

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +            with torch.no_grad():
Are you sure e need `torch.no_grad()` only in the decoder?

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +                video_by_batch = self.model.decode(latents[0])
Same as above, I believe it requires a cascaded for-loop through the frame-dimension.

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +            videos.append(video_by_batch[0])
Same as above, I would use `torch.stack`.

2022-10-06 19:40 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +        video_tensor = torch.stack(videos).permute(0, 2, 1, 3, 4)
Yes using this but without the appending to an empty array.

2022-10-06 19:49 UTC, oxjohanndiep reviewed
Minor comments regarding your two methods for encoding and decoding images. I believe you do not even use it at the end, as for video encoding/decoding you are calling directly the Huggingface class.

2022-10-06 19:49 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +    def encode_img_latents(self,imgs):
Why do we need this method? Are we gonna use it?

2022-10-06 19:49 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +    def decode_img_latents(self, latents):
Why do we need this method, are we gonna use it?

2022-10-07 05:34 UTC, merged

2022-10-07 07:44 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +            latent_dists_1_video = self.model.encode(video_by_batch[i])
The .encode function handles batches of inputs. So I believe that the function will handle the frames (as if a batch of images) and then the for loop handles a batch of video inputs.

2022-10-07 07:46 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +        imgs = imgs.detach().cpu().permute(0, 2, 3, 1).numpy()
My comment was only for line 58

2022-10-07 07:48 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +    def encode_img_latents(self,imgs):
No! Guess it is just the legacy code

2022-10-07 07:49 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +        latent_samples *= 0.18215
Unsure - will look into this further

2022-10-07 07:49 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +    # Can pass in images of any size - all dims recuded by a factor of 8
Have corrected!!

2022-10-07 07:50 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +    def decode_img_latents(self, latents):
Again, no but is the base code

2022-10-07 07:51 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +            with torch.no_grad():
I guess we need it everywhere as we wont be updating weights of this model or of any of the inputs.

2022-10-07 08:04 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +    # inputs: Images (b, h, w)
Update comment accordingly

2022-10-07 08:04 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +        img_arr = 2 * (img_arr - 0.5)
Thanks for this! Will have a look at how this translates to video inputs. I think we will not have to account for this as it is handled in the gif_to_tensor function

2022-10-07 08:05 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +    # outputs: (b, 4, dh*8, dw*8)
Updates

2022-10-07 08:05 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +        imgs = (imgs[0] / 2 + 0.5).clamp(0, 1)
Updated

2022-10-07 08:05 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +    # outputs: Encodings as tensor (b, 4, h/8, w/8)
Updated

2022-10-07 08:05 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +        if vid.dim != 5:
Updated

2022-10-07 08:07 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +            latent_samples.append(latent_sample)
I do not think this will work without an if condition. Given the first iteration of the for loop there is not a base tensor with which we want to stack.

2022-10-07 08:10 UTC, Ljackson-su commented on mindglass_code/autoencoder.py
> +            latent_samples.append(latent_sample)
I am unsure how this will work since on the first iteration of the for loop there is not a base tensor to use

2022-10-07 18:35 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +            latent_dists_1_video = self.model.encode(video_by_batch[i])
I see, smart choice!

2022-10-07 18:39 UTC, oxjohanndiep commented on mindglass_code/autoencoder.py
> +            latent_samples.append(latent_sample)
Trying with some mock-data, this approach works great!

2022-10-08 05:10 UTC, oxjohanndiep commented
Accidently pre-merged this `feature_1` into `develop`, which is why this pull-request does not contain the new commits to `feature_1`. The merge into `develop` has now been closed with a hotfix.